[package]
name = "fastq"
version = "0.4.1"
authors = ["Adrian Seyboldt <adrian.seyboldt@gmail.com>"]
description = "A parser for fastq"
license = "MIT"
repository = "https://github.com/aseyboldt/fastq-rs"
documentation = "https://docs.rs/fastq"
readme = "README.md"
keywords = ["bio", "fastq", "parser"]

[dependencies]
memchr = ">=0.1"
lz4 = "^1.20"
#flate2 = { version = "^0.2", features = ["zlib"], default-features = false }
flate2 = { git = "https://github.com/veldsla/flate2-rs.git", branch = "multigz"}

[dev-dependencies]
parasailors = "^0.3"
bio = "^0.10"
